project:
  type: website
  output-dir: ../docs/demos

engine: knitr

website:
  title: "ewing Demos"
  navbar:
    left:
      - href: https://byandell.github.io/ewing/index.html
        text: Home
      - href: index.qmd
        text: Gallery
      - href: sysetholApp.qmd
        text: sysethol
      - href: IsleRoyaleApp.qmd
        text: IsleRoyale
      - text: Tools
        menu:
          - href: fivePlotApp.qmd
            text: fivePlot
          - href: fiveShowApp.qmd
            text: fiveShow
          - href: tempApp.qmd
            text: temp
          - href: triangleApp.qmd
            text: triangle
          - href: hexmoveApp.qmd
            text: hexmove
    right:
      - icon: github
        href: https://github.com/byandell/ewing

format:
  html:
    theme: cosmo
    toc: true
    toc-depth: 2
    embed-resources: false
    self-contained: false

filters:
  - quarto-ext/shinylive
